### ISSUE TITLE
Make deployment pipeline ready for building branches

### ISSUE THREAD

**Issue by britter** [scrum-for-developers/scrum-for-developers-infra#2]
The deployment pipeline should also build all commits pushed to branches, and not only commits on the master branch. It would be even better if we could manage to start a new test environement and execute the acceptance tests against it, using additional docker containers. The problem here is, that the host is resonsible for starting containers and not jenkins (which is running inside docker itself).

**Comment by AndreasEK** [comment]
regarding sonar, there's a parameter that might come in handy:
-Dsonar.branch
-Dsonar.projectKey

http://docs.sonarqube.org/display/SONAR/Analysis+Parameters
